import os
import re
import json
from pathlib import Path
from PIL import Image

# --- CONFIGURATION ---
INPUT_DIR = Path("input_scans")
THUMB_DIR = Path("assets/cards/thumbs")
FULL_DIR = Path("assets/cards/full")
OUTPUT_JS = Path("library-cards.js")

# Target Max Widths (px)
THUMB_MAX_WIDTH = 600
FULL_MAX_WIDTH = 1600

# WebP Quality (1-100)
THUMB_QUALITY = 80
FULL_QUALITY = 85

VALID_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".tiff", ".bmp"}


def resize_and_save(img: Image.Image, max_width: int, output_path: Path, quality: int):
    """Resizes an image maintaining aspect ratio and exports to WebP."""
    w, h = img.size
    if w > max_width:
        new_h = int((max_width / w) * h)
        resized_img = img.resize((max_width, new_h), Image.Resampling.LANCZOS)
    else:
        resized_img = img.copy()

    # Handle color modes for WebP export
    if resized_img.mode in ("RGBA", "LA") or (resized_img.mode == "P" and "transparency" in resized_img.info):
        resized_img = resized_img.convert("RGBA")
    else:
        resized_img = resized_img.convert("RGB")

    resized_img.save(output_path, "WEBP", quality=quality, optimize=True)


def parse_filename(stem: str):
    """
    Extracts card_id, side (front/back), title, and year from filename.
    Pattern examples: 
      - '01_Toronto-Public-Library_1994_front'
      - 'card-01_front'
    """
    stem_lower = stem.lower()
    
    # Determine Side
    if stem_lower.endswith("_front") or stem_lower.endswith("-front"):
        side = "front"
        base_name = stem[:-6]
    elif stem_lower.endswith("_back") or stem_lower.endswith("-back"):
        side = "back"
        base_name = stem[:-5]
    else:
        side = "front"
        base_name = stem

    parts = base_name.split("_")
    card_id = parts[0]
    
    # Extract 4-digit year if present
    year_match = re.search(r"\b(19\d{2}|20\d{2})\b", base_name)
    year = year_match.group(1) if year_match else "N/A"

    # Derive human-readable title
    if len(parts) > 1:
        # Title is second part if standard underscore pattern used
        title = parts[1].replace("-", " ").strip()
    else:
        title = card_id.replace("-", " ").title()

    return card_id, side, title, year


def main():
    if not INPUT_DIR.exists():
        INPUT_DIR.mkdir(parents=True, exist_ok=True)
        print(f"Created '{INPUT_DIR}' directory. Drop your raw card scans inside and run again.")
        return

    THUMB_DIR.mkdir(parents=True, exist_ok=True)
    FULL_DIR.mkdir(parents=True, exist_ok=True)

    # Group input files by card_id
    grouped_cards = {}

    for file_path in INPUT_DIR.iterdir():
        if file_path.suffix.lower() not in VALID_EXTENSIONS:
            continue

        card_id, side, title, year = parse_filename(file_path.stem)

        if card_id not in grouped_cards:
            grouped_cards[card_id] = {
                "id": card_id,
                "title": title,
                "year": year,
                "files": {}
            }
        grouped_cards[card_id]["files"][side] = file_path

    if not grouped_cards:
        print(f"No valid image files found in '{INPUT_DIR}'.")
        return

    cards_js_data = []

    print(f"Processing {len(grouped_cards)} card(s)...\n")

    for card_id, info in sorted(grouped_cards.items()):
        card_entry = {
            "id": card_id,
            "title": info["title"],
            "year": info["year"],
            "location": "Archive",
            "tags": ["archive"],
            "thumbFront": None,
            "fullFront": None,
            "thumbBack": None,
            "fullBack": None,
            "notes": ""
        }

        for side in ["front", "back"]:
            file_path = info["files"].get(side)
            if not file_path:
                continue

            output_filename = f"{card_id}-{side}.webp"
            thumb_out = THUMB_DIR / output_filename
            full_out = FULL_DIR / output_filename

            try:
                with Image.open(file_path) as img:
                    # Generate Full WebP
                    resize_and_save(img, FULL_MAX_WIDTH, full_out, FULL_QUALITY)
                    # Generate Thumb WebP
                    resize_and_save(img, THUMB_MAX_WIDTH, thumb_out, THUMB_QUALITY)

                # Store relative web paths
                card_entry[f"thumb{side.capitalize()}"] = f"assets/cards/thumbs/{output_filename}"
                card_entry[f"full{side.capitalize()}"] = f"assets/cards/full/{output_filename}"

                print(f"  ✓ Processed [{side.upper()}]: {file_path.name} -> WebP")

            except Exception as e:
                print(f"  ✗ Failed to process {file_path.name}: {e}")

        cards_js_data.append(card_entry)

    # Output library-cards.js
    js_content = f"// Auto-generated by process_cards.py\nconst libraryCards = {json.dumps(cards_js_data, indent=2)};\n"
    
    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"\nFinished! Processed {len(cards_js_data)} cards.")
    print(f"Updated '{OUTPUT_JS}', images saved to '{THUMB_DIR}' & '{FULL_DIR}'.")


if __name__ == "__main__":
    main()